apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 81



---

apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  selector:
    app.kubernetes.io/name: dev-pod
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81


