apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: prod-service
spec:
  selector:
    app.kubernetes.io/name: prod-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80