apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data: 
  password: slfjvnc==
  token: jdgbjgndsdmdjdk==


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data: 
  url: localhost
  